# Generated by Django 3.0.7 on 2020-07-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_pessoa', '0002_paciente_responsavel_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='path_imagem',
            field=models.ImageField(blank=True, upload_to='images/07/13/2020'),
        ),
    ]
