# Generated by Django 3.0.7 on 2020-07-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_pessoa', '0003_paciente_path_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='path_imagem',
            field=models.ImageField(blank=True, upload_to='images/07/15/2020'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='protocolos',
            field=models.TextField(default='{}'),
        ),
    ]
