# Generated by Django 3.0.7 on 2020-07-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_pessoa', '0004_auto_20200715_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='path_paciente',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='path_imagem',
            field=models.ImageField(blank=True, upload_to='images/07/20/2020'),
        ),
    ]
