# Generated by Django 3.0.7 on 2020-07-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_pessoa', '0005_auto_20200720_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='path_paciente',
            new_name='uuid_paciente',
        ),
    ]
